Minor changes on workflow file

diff --git a/.github/workflows/1_continuous_integration.yml b/.github/workflows/1_continuous_integration.yml
--- a/.github/workflows/1_continuous_integration.yml
+++ b/.github/workflows/1_continuous_integration.yml
@@ -17,6 +17,7 @@ env:
   MLFLOW_EXPERIMENT_NAME: ${{ vars.MLFLOW_EXPERIMENT_NAME }}
   MLFLOW_MODEL_NAME: ${{ vars.MLFLOW_MODEL_NAME }}
   API_URI: ${{ vars.API_URI }}
+  CA_CERT: ${{ secrets.CA_CERT }}
 
 jobs:
   VPN-connection:
@@ -29,15 +30,27 @@ jobs:
         run: |
           sudo apt update
           sudo apt install -y openvpn openvpn-systemd-resolved
-      - name: Connect to VPN
-        uses: "kota65535/github-openvpn-connect-action@v2"
+      - name: Connect to DEI VPN
+        uses: kota65535/github-openvpn-connect-action@v2
         with:
           config_file: .github/workflows/client.ovpn
-          username: ${{ secrets.OVPN_USERNAME }}
-          password: ${{ secrets.OVPN_PASSWORD }}
+          username: ${{ secrets.VPN_USERNAME }}
+          password: ${{ secrets.VPN_PASSWORD }}
+          # The action creates a temp file from this secret and tells OpenVPN to use it
+          ca_crt: ${{ secrets.VPN_CA_CERT }}
+
+      - name: Verify Connection
+        run: |
+          echo "VPN Status:"
+          ifconfig tap0 || echo "tap0 interface not found"
+          
+          echo "Testing connectivity:"
+          ping -c 2 10.17.0.207 || echo "Ping failed (Note: ICMP might be blocked)"
+
 
   test-unit:
     runs-on: ubuntu-latest
+    needs: VPN-connection
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5
